language: python

branches:
  only:
    - master

sudo: true

dist: xenial

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  - pip install -U pip setuptools wheel tox-travis coveralls

script:
  - tox

after_success:
- coveralls