language: python

branches:
  only:
    - master

sudo: false

matrix:
  include:
    - python: 3.6

install:
  - pip install -U pip setuptools wheel tox-travis coveralls

script:
  - tox

after_success:
- coveralls