package:
  name: darr
  version: "0.1.2"

source:
  path: ..

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - darr

about:
  license: BSD
  license_file: LICENSE