package:
  name: darr
  version: "0.1.3a1"

source:
  git_rev: v0.1.3a1
  git_url: https://github.com/gbeckers/darr.git

requirements:
  build:
    - python >=3.6

  run:
    - python >=3.6
    - numpy >=1.13

test:
  imports:
    - darr

about:
  home: https://github.com/gbeckers/darr
  license: BSD
  license_file: LICENSE