package:
  name: darr
  version: "0.1.3a3"

source:
  git_rev: v0.1.3a3
  git_url: https://github.com/gbeckers/darr.git

requirements:
  build:
    - python >=3.6
    - numpy >=1.13

  run:
    - python >=3.6
    - numpy >=1.13

build:
  noarch: python

test:
  imports:
    - darr

about:
  home: https://github.com/gbeckers/darr
  license: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'